application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: guestbook.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- datastore_admin: on
